# Generated by Django 5.2.7 on 2026-01-15 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_trabajo', '0002_herramienta_ordenherramientarequerida_vehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='BODEGA, INSTALADO, RETIRADO, REPARACION, BAJA, etc.', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Estados de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BODEGA_DELCO', 'Bodega Delco'), ('BODEGA_CONTRATISTA', 'Bodega Contratista'), ('TECNICO', 'Custodia Técnico'), ('CLIENTE', 'Instalado en Cliente'), ('PROVEEDOR', 'Proveedor/Reparación')], max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('identificador_interno', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('en_custodia_de', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidores_en_custodia', to=settings.AUTH_USER_MODEL)),
                ('estado_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidores', to='inventario.estadoinventario')),
                ('ubicacion_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidores', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Medidores',
            },
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('en_custodia_de', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_en_custodia', to=settings.AUTH_USER_MODEL)),
                ('estado_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modems', to='inventario.estadoinventario')),
                ('ubicacion_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modems', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Módems',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega a técnico'), ('RECEPCION', 'Recepción en bodega'), ('DEVOLUCION', 'Devolución'), ('INSTALACION', 'Instalación en cliente'), ('RETIRO', 'Retiro de cliente')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ordenes_trabajo.ordentrabajo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(help_text='Número telefónico', max_length=20, unique=True)),
                ('ip_fija', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('serie_plastico', models.CharField(max_length=50, unique=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('en_custodia_de', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards_en_custodia', to=settings.AUTH_USER_MODEL)),
                ('estado_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simcards', to='inventario.estadoinventario')),
                ('ubicacion_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simcards', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'SIM Cards',
            },
        ),
        migrations.CreateModel(
            name='MovimientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('MEDIDOR', 'Medidor'), ('SIM', 'SIM Card'), ('MODEM', 'Módem')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('medidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.medidor')),
                ('modem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modem')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.movimientoinventario')),
                ('simcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.simcard')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Movimiento',
            },
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['-fecha_hora'], name='inventario__fecha_h_b6a1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='inventario__tipo_b85d84_idx'),
        ),
        migrations.AddIndex(
            model_name='medidor',
            index=models.Index(fields=['serie'], name='inventario__serie_67c6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='medidor',
            index=models.Index(fields=['estado_inventario'], name='inventario__estado__c2e292_idx'),
        ),
    ]
