# Generated by Django 5.2.7 on 2026-01-19 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modem',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='modem',
            name='modelo',
        ),
        migrations.AddField(
            model_name='modem',
            name='bodega',
            field=models.CharField(blank=True, help_text='Bodega de origen o referencia', max_length=100),
        ),
        migrations.AddField(
            model_name='modem',
            name='caja',
            field=models.CharField(blank=True, help_text='Número de caja de recepción', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modem',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_asignados', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='modem',
            name='entregado_a',
            field=models.ForeignKey(blank=True, help_text='Usuario a quien se entregó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modem',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modem',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Fecha de entrega al técnico', null=True),
        ),
        migrations.AddField(
            model_name='modem',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha de recepción en bodega', null=True),
        ),
        migrations.AddField(
            model_name='modem',
            name='modulo',
            field=models.CharField(blank=True, help_text='Módulo o tipo de modem', max_length=100),
        ),
        migrations.AddField(
            model_name='modem',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modem',
            name='en_custodia_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_en_custodia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modem',
            name='estado_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modems', to='inventario.estadoinventario'),
        ),
        migrations.AlterField(
            model_name='modem',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modem',
            name='ubicacion_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modems', to='inventario.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='modem',
            index=models.Index(fields=['serie'], name='inventario__serie_e5263f_idx'),
        ),
        migrations.AddIndex(
            model_name='modem',
            index=models.Index(fields=['caja'], name='inventario__caja_7e5207_idx'),
        ),
        migrations.AddIndex(
            model_name='modem',
            index=models.Index(fields=['estado_inventario'], name='inventario__estado__162432_idx'),
        ),
    ]
