# Generated by Django 5.2.7 on 2026-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_medidor_fields_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='caja',
            field=models.CharField(blank=True, help_text='Número de caja de recepción (múltiples medidores por caja)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modem',
            name='caja',
            field=models.CharField(blank=True, help_text='Número de caja de recepción (múltiples módems por caja)', max_length=50, null=True),
        ),
    ]
