# Generated by Django 5.2.7 on 2026-01-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('inventario', '0004_alter_medidor_caja_alter_modem_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='abonado',
            field=models.CharField(blank=True, default='', help_text='Número de abonado o identificador del operador', max_length=50),
        ),
        migrations.AddField(
            model_name='simcard',
            name='apn',
            field=models.CharField(blank=True, default='', help_text='Access Point Name (APN) configurado', max_length=255),
        ),
        migrations.AddField(
            model_name='simcard',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente al que está asignada la SIM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards_asignadas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='direccion_ip',
            field=models.CharField(blank=True, default='', help_text='Dirección IP asignada', max_length=50),
        ),
        migrations.AddField(
            model_name='simcard',
            name='entregado_a_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de quien recibe (del Excel)', max_length=255),
        ),
        migrations.AddField(
            model_name='simcard',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Fecha de entrega al técnico o instalación', null=True),
        ),
        migrations.AddField(
            model_name='simcard',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha de recepción en bodega', null=True),
        ),
        migrations.AddField(
            model_name='simcard',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI del modem/equipo asociado', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='simcard',
            name='medidor',
            field=models.ForeignKey(blank=True, help_text='Medidor asociado a esta SIM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards_asociadas', to='inventario.medidor'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='operador',
            field=models.CharField(blank=True, default='', help_text='Operador telefónico (ENTEL, CLARO, MOVISTAR, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='estado_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simcards', to='inventario.estadoinventario'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='ip_fija',
            field=models.CharField(blank=True, help_text='IP fija (legacy - usar direccion_ip)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='msisdn',
            field=models.CharField(blank=True, help_text='Número telefónico (legacy)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Proveedor (legacy - usar operador)', max_length=100),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='serie_plastico',
            field=models.CharField(blank=True, help_text='Número de serie del plástico (legacy)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='ubicacion_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simcards', to='inventario.ubicacion'),
        ),
    ]
