# Generated by Django 5.2.7 on 2026-01-27 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('inventario', '0005_simcard_abonado_simcard_apn_simcard_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI del módem (identificador único)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modem',
            name='ip',
            field=models.CharField(blank=True, default='', help_text='Dirección IP del módem', max_length=50),
        ),
        migrations.AddField(
            model_name='modem',
            name='irregularidad',
            field=models.TextField(blank=True, default='', help_text='Irregularidades detectadas'),
        ),
        migrations.AddField(
            model_name='modem',
            name='marca_secundaria',
            field=models.CharField(blank=True, default='', help_text='Marca secundaria o adicional', max_length=100),
        ),
        migrations.AddField(
            model_name='modem',
            name='medidor',
            field=models.ForeignKey(blank=True, help_text='Medidor asociado a este módem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_asociados', to='inventario.medidor'),
        ),
        migrations.AddField(
            model_name='modem',
            name='modelo',
            field=models.CharField(blank=True, default='', help_text='Modelo del módem', max_length=100),
        ),
        migrations.AddField(
            model_name='modem',
            name='proyecto',
            field=models.CharField(blank=True, default='', help_text='Proyecto asociado', max_length=255),
        ),
        migrations.AddField(
            model_name='modem',
            name='puerto',
            field=models.CharField(blank=True, default='', help_text='Puerto de conexión', max_length=20),
        ),
        migrations.AddField(
            model_name='modem',
            name='retirado',
            field=models.CharField(blank=True, default='', help_text='Información de retiro', max_length=50),
        ),
        migrations.AddField(
            model_name='modem',
            name='serie_secundaria',
            field=models.CharField(blank=True, default='', help_text='Serie secundaria', max_length=50),
        ),
        migrations.AddField(
            model_name='modem',
            name='tecnico_responsable',
            field=models.CharField(blank=True, default='', help_text='Nombre del técnico responsable (del Excel)', max_length=255),
        ),
        migrations.AlterField(
            model_name='modem',
            name='bodega',
            field=models.CharField(blank=True, help_text='Bodega de origen', max_length=100),
        ),
        migrations.AlterField(
            model_name='modem',
            name='caja',
            field=models.CharField(blank=True, help_text='Número de caja de recepción', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modem',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente al que está asignado el módem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_asignados', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='modem',
            name='entregado_a',
            field=models.ForeignKey(blank=True, help_text='Usuario a quien se entregó (legacy - usar tecnico_responsable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modem',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Marca del módem', max_length=100),
        ),
        migrations.AlterField(
            model_name='modem',
            name='modulo',
            field=models.CharField(blank=True, help_text='Módulo o tipo (legacy)', max_length=100),
        ),
        migrations.AlterField(
            model_name='modem',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones del administrativo'),
        ),
        migrations.AlterField(
            model_name='modem',
            name='serie',
            field=models.CharField(help_text='Número de serie del módem', max_length=50, unique=True),
        ),
    ]
