# Generated by Django 5.2.7 on 2026-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_modem_imei_modem_ip_modem_irregularidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(help_text='ID único del formulario en MoreApp', max_length=255, unique=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se recibió')),
                ('num_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Cliente')),
                ('num_orden', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Orden')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('resultado_visita', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado de Visita')),
                ('estado_medidor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del Medidor')),
                ('foto_fachada_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Foto')),
                ('datos_completos', models.JSONField(blank=True, default=dict, verbose_name='JSON completo')),
                ('procesado', models.BooleanField(default=False, help_text='Si ya se procesó')),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verificación de Medidor',
                'verbose_name_plural': 'Verificaciones de Medidores',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
