# Generated by Django 4.2.29 on 2026-03-20 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0007_verificacionmedidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente (editable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidores_asignados', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='entregado_a',
            field=models.ForeignKey(blank=True, help_text='Usuario a quien se entregó (editable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidores_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='estado_inventario',
            field=models.ForeignKey(blank=True, help_text='Estado del medidor (editable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medidores', to='inventario.estadoinventario'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Fecha de entrega al técnico (editable)', null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='fecha_recepcion',
            field=models.DateField(blank=True, editable=False, help_text='Fecha de recepción en bodega (solo lectura)', null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='marca',
            field=models.CharField(blank=True, editable=False, help_text='Marca (solo lectura)', max_length=100),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='modulo',
            field=models.BooleanField(blank=True, help_text='¿Tiene módulo? (Sí/No)', null=True),
        ),
    ]
