# Generated by Django 4.2.29 on 2026-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_medidor_cliente_alter_medidor_entregado_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='entregado_a_info',
            field=models.CharField(blank=True, help_text='Información textual de ENTREGADO A desde Excel (para corrección manual)', max_length=255),
        ),
    ]
