# Generated by Django 4.2.29 on 2026-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_medidor_entregado_a_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('IMPORTACION', 'Importación masiva'), ('ENTREGA', 'Entrega a técnico'), ('RECEPCION', 'Recepción en bodega'), ('DEVOLUCION', 'Devolución'), ('INSTALACION', 'Instalación en cliente'), ('RETIRO', 'Retiro de cliente'), ('ELIMINACION', 'Eliminación de registro')], max_length=20),
        ),
    ]
