# Generated by Django 4.2.29 on 2026-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='proyecto',
            field=models.CharField(blank=True, default='', help_text='Proyecto asociado al medidor', max_length=255),
        ),
        migrations.AddField(
            model_name='simcard',
            name='proyecto',
            field=models.CharField(blank=True, default='', help_text='Proyecto asociado a la SIM', max_length=255),
        ),
    ]
