# Generated by Django 4.2.29 on 2026-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_estados_operativos_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='tipo_medidor',
            field=models.CharField(choices=[('DIRECTO', 'Directo'), ('INDIRECTO', 'Indirecto')], default='DIRECTO', help_text='Subtipo operativo obligatorio: DIRECTO o INDIRECTO', max_length=20),
        ),
    ]
