# Generated by Django 4.2.29 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_medidor_tipo_medidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='origen_sistema',
            field=models.CharField(choices=[('MOREAPP', 'MoreApp (automático)'), ('MANUAL', 'Manual (usuario)'), ('IMPORTACION', 'Importación masiva'), ('SISTEMA', 'Sistema interno')], default='MANUAL', help_text='Qué proceso generó este movimiento', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('IMPORTACION', 'Importación masiva'), ('ENTREGA', 'Entrega a técnico'), ('RECEPCION', 'Recepción en bodega'), ('DEVOLUCION', 'Devolución'), ('INSTALACION', 'Instalación en cliente'), ('RETIRO', 'Retiro de cliente'), ('ELIMINACION', 'Eliminación de registro'), ('AJUSTE', 'Ajuste manual'), ('CORRECCION', 'Corrección de datos'), ('MOREAPP', 'Actualización MoreApp')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['origen_sistema'], name='inventario__origen__ecb5fb_idx'),
        ),
    ]
