# Generated by Django 4.2.30 on 2026-07-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0017_campos_manual_y_estado_en_trayecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: oculto en inventario, histórico en movimientos'),
        ),
        migrations.AddField(
            model_name='medidor',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidores_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medidor',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modem',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: oculto en inventario, histórico en movimientos'),
        ),
        migrations.AddField(
            model_name='modem',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modems_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modem',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='datos_eliminacion',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot inmutable de la ficha eliminada (sin archivos binarios)'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='entidad_eliminada',
            field=models.CharField(blank=True, choices=[('MEDIDOR', 'Medidor'), ('SIM', 'SIM Card'), ('MODEM', 'Módem'), ('CLIENTE', 'Cliente'), ('ORDEN_TRABAJO', 'Orden de trabajo'), ('MOREAPP', 'Reporte MoreApp')], db_index=True, default='', help_text='Tipo de entidad eliminada (solo movimientos ELIMINACION)', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='entidad_id',
            field=models.CharField(blank=True, default='', help_text='PK original de la entidad eliminada', max_length=64),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='identificador_entidad',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador legible (serie, submission_id, número cliente, OT#)', max_length=255),
        ),
        migrations.AddField(
            model_name='simcard',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: oculto en inventario, histórico en movimientos'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simcard',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='medidor',
            index=models.Index(fields=['eliminado'], name='inventario__elimina_b2c503_idx'),
        ),
        migrations.AddIndex(
            model_name='modem',
            index=models.Index(fields=['eliminado'], name='inventario__elimina_54578e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['entidad_eliminada'], name='inventario__entidad_401f03_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['identificador_entidad'], name='inventario__identif_331a37_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['eliminado'], name='inventario__elimina_e2d587_idx'),
        ),
    ]
