# Generated by Django 4.2.30 on 2026-08-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_soft_delete_y_snapshot_eliminaciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificacionMedidor',
        ),
        migrations.RemoveIndex(
            model_name='medidor',
            name='inventario__serie_67c6f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='medidor',
            name='inventario__elimina_b2c503_idx',
        ),
        migrations.RemoveIndex(
            model_name='modem',
            name='inventario__serie_e5263f_idx',
        ),
        migrations.RemoveIndex(
            model_name='modem',
            name='inventario__elimina_54578e_idx',
        ),
        migrations.RemoveIndex(
            model_name='simcard',
            name='inventario__elimina_e2d587_idx',
        ),
    ]
