# Generated by Django 4.2.30 on 2026-07-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='catalogodiagnostico',
            new_name='catalogos_c_categor_9f5476_idx',
            old_name='catalogos_c_categor_0f0f0f_idx',
        ),
    ]
