# Generated by Django 4.2.29 on 2026-08-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_proyecto'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proyecto',
            new_name='catalogos_p_activo_8181a5_idx',
            old_name='catalogos_p_activo_nombre_idx',
        ),
    ]
