# Generated by Django 5.2.7 on 2026-01-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_trabajo', '0002_herramienta_ordenherramientarequerida_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionMoreAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], max_length=20)),
                ('payload_crudo', models.JSONField(help_text='Contenido completo recibido')),
                ('mensaje_error', models.TextField(blank=True)),
                ('adjunto_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracion_origen', to='ordenes_trabajo.adjuntoorden')),
                ('orden_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integraciones_moreapp', to='ordenes_trabajo.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Integración MoreApp',
                'verbose_name_plural': 'Integraciones MoreApp',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['estado'], name='integracion_estado_fcfaea_idx'), models.Index(fields=['-fecha_hora'], name='integracion_fecha_h_70d220_idx')],
            },
        ),
    ]
