# Generated by Django 4.2.30 on 2026-08-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_desacople_fks_ordenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegracionMoreAppLog',
        ),
    ]
