# Generated by Django 4.2.30 on 2026-07-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='web_auditlo_action_e4df12_idx',
            old_name='web_auditlo_action_7c61bb_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='web_auditlo_entity_75906b_idx',
            old_name='web_auditlo_entity_a8477f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='web_auditlo_entity__8e9166_idx',
            old_name='web_auditlo_entity__78f8a5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='web_auditlo_created_f1c247_idx',
            old_name='web_auditlo_created_826837_idx',
        ),
    ]
