# Generated by Django 5.2.7 on 2026-01-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EQUIPOS', 'Importar Equipos (Medidores/SIM/Módems)'), ('CLIENTES', 'Importar Clientes'), ('MOVIMIENTOS', 'Importar Movimientos de Inventario')], max_length=30)),
                ('archivo_original', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando...'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PROCESANDO', max_length=20)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('exitosas', models.PositiveIntegerField(default=0)),
                ('fallidas', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Importaciones Excel',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionExcelError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('data_cruda', models.TextField(help_text='Contenido de la fila que falló')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='importaciones.importacionexcel')),
            ],
            options={
                'verbose_name_plural': 'Errores de Importación',
                'ordering': ['numero_fila'],
            },
        ),
        migrations.AddIndex(
            model_name='importacionexcel',
            index=models.Index(fields=['tipo'], name='importacion_tipo_31cc86_idx'),
        ),
        migrations.AddIndex(
            model_name='importacionexcel',
            index=models.Index(fields=['estado'], name='importacion_estado_c8930b_idx'),
        ),
        migrations.AddIndex(
            model_name='importacionexcel',
            index=models.Index(fields=['usuario'], name='importacion_usuario_ceb0fa_idx'),
        ),
    ]
