# Generated by Django 4.2.29 on 2026-03-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionexcel',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Nombre del usuario que realizó la importación (histórico)', max_length=255),
        ),
        migrations.AlterField(
            model_name='importacionexcel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
