# Generated by Django 4.2.30 on 2026-07-30 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0017_validacion_comunicacion_ot'),
        ('clientes', '0011_carga_administrativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('VALIDACION_OT', 'Validación de OT'), ('VERIFICACION_SCI4', 'Actualización base comercial (SCi4)'), ('REVISION_MOREAPP', 'Revisión MoreApp'), ('COMUNICACION', 'Validación de comunicación'), ('VERIFICACION', 'Verificación administrativa'), ('OTRO', 'Otro')], db_index=True, default='VERIFICACION', max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('url_referencia', models.CharField(blank=True, help_text='Enlace directo a la pantalla de trabajo', max_length=500)),
                ('observaciones', models.TextField(blank=True, help_text='Notas de avance o resultado al completar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Administrativo responsable de la carga', limit_choices_to={'is_active': True, 'rol__in': ['ADMIN', 'ADMINISTRATIVO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_admin', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_creadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_admin', to='ordenes_trabajo.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Carga administrativa',
                'verbose_name_plural': 'Cargas administrativas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', '-fecha_creacion'], name='cargas_carg_estado_a11caf_idx'), models.Index(fields=['asignado_a', 'estado'], name='cargas_carg_asignad_d0830e_idx'), models.Index(fields=['tipo', 'estado'], name='cargas_carg_tipo_6d921f_idx'), models.Index(fields=['orden'], name='cargas_carg_orden_i_bc80ad_idx'), models.Index(fields=['cliente'], name='cargas_carg_cliente_fbbdd2_idx')],
            },
        ),
    ]
