# Generated by Django 4.2.30 on 2026-08-07 17:19

import config.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargas', '0001_carga_administrativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografía / captura de pantalla'), ('PDF', 'PDF'), ('MOREAPP', 'Archivo MoreApp'), ('OTRO', 'Otro')], default='FOTO', max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(help_text='Archivo en Registros/Evidencias/adjuntos_cargas', storage=config.storage.EvidenciasStorage(), upload_to=config.storage.evidencia_upload_to)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('hash_archivo', models.CharField(blank=True, max_length=64)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='cargas.cargaadministrativa')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_carga_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de carga',
                'verbose_name_plural': 'Adjuntos de cargas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['carga'], name='cargas_adju_carga_i_3ae21d_idx'), models.Index(fields=['tipo'], name='cargas_adju_tipo_4b80da_idx')],
            },
        ),
    ]
