# Generated by Django 4.2.30 on 2026-08-07 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargas', '0002_adjunto_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntocarga',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='adjuntocarga',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_carga_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjuntocarga',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='adjuntocarga',
            index=models.Index(fields=['carga', 'eliminado'], name='cargas_adju_carga_i_5c6c74_idx'),
        ),
    ]
