# Generated by Django 4.2.29 on 2026-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0006_cargaadministrativa_asignado_texto'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cargaadministrativa',
            new_name='cargas_carg_proyect_c28fd2_idx',
            old_name='cargas_carg_proyec_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='cargaadministrativa',
            new_name='cargas_carg_elimina_360334_idx',
            old_name='cargas_carg_elimin_4f9a2c_idx',
        ),
        migrations.AlterField(
            model_name='cargaadministrativa',
            name='url_referencia',
            field=models.CharField(blank=True, help_text='Enlace directo a la pantalla de trabajo (p. ej. listado filtrado por proyecto)', max_length=500),
        ),
    ]
