# coding: utf-8
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Intentar cargar variables de entorno desde .env, pero no fallar si dotenv no esta disponible
try:
    from dotenv import load_dotenv  # type: ignore
    BASE_DIR = Path(__file__).resolve().parent.parent
    current_settings_module = os.getenv('DJANGO_SETTINGS_MODULE', '')
    if current_settings_module != 'config.settings_production':
        load_dotenv(BASE_DIR / '.env')
except ImportError:
    # Si python-dotenv no esta instalado, usar las variables de entorno del servidor
    BASE_DIR = Path(__file__).resolve().parent.parent
    import logging
    logging.warning('python-dotenv no esta instalado. Usando variables de entorno del servidor.')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ze21q-q$&2(!*!orvf)w-_s&xttn0^((b+2qzlvew&y$hfb%23'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    'inventario.delcochile',          # el dominio donde corre la app
    'www.inventario.delcochile',      # opcional, si existe
    'localhost',                      # para acceso local/ssh
]
# Solo agregar 127.0.0.1 en modo desarrollo
if os.getenv('DJANGO_SETTINGS_MODULE', '') != 'config.settings_production':
    ALLOWED_HOSTS.append('127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    # Apps locales
    'usuarios.apps.UsuariosConfig',
    'ordenes_trabajo.apps.OrdenesTrabajoConfig',
    'web.apps.WebConfig',
    'clientes.apps.ClientesConfig',
    'inventario.apps.InventarioConfig',
    'importaciones.apps.ImportacionesConfig',
    'integraciones.apps.IntegracionesConfig',
    'catalogos.apps.CatalogosConfig',
    'reportes.apps.ReportesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'web.middleware.AbsoluteSessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.moreapp_aviso',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_name = os.getenv('DB_NAME')
db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')
db_host = os.getenv('DB_HOST')
db_port = os.getenv('DB_PORT')

if all([db_name, db_user, db_host]):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password or '',
            'HOST': db_host,
            'PORT': db_port or '3306',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Archivos de usuario (Media)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Evidencias de órdenes de trabajo (adjuntos PDF, fotos, informes)
EVIDENCIAS_ROOT = BASE_DIR / 'Registros' / 'Evidencias'
EVIDENCIAS_URL = '/registros/evidencias/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Usuario'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Sesion de seguridad: expiracion absoluta a 8 horas.
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '28800'))
ABSOLUTE_SESSION_TIMEOUT_SECONDS = int(os.getenv('ABSOLUTE_SESSION_TIMEOUT_SECONDS', '28800'))
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True

# Cache local (LocMem): KPIs, avisos MoreApp y alcances operativos.
# En hosting compartido no hay Redis; esto reduce COUNTs repetidos por request.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'delcoplata-locmem',
        'TIMEOUT': 120,
        'OPTIONS': {'MAX_ENTRIES': 2000},
    }
}

# Modo de integracion MoreApp
MOREAPP_WEBHOOK_REALTIME_ENABLED = os.getenv('MOREAPP_WEBHOOK_REALTIME_ENABLED', 'true').strip().lower() == 'true'
# Autosync en GET de dashboard/listados: OFF por defecto (bloquea el request con muchos JSON).
# Activar solo si hace falta: MOREAPP_AUTO_SYNC_ENABLED=true. Preferir botón manual / cron.
MOREAPP_AUTO_SYNC_ENABLED = os.getenv('MOREAPP_AUTO_SYNC_ENABLED', 'false').strip().lower() == 'true'
MOREAPP_AUTO_SYNC_INTERVAL_SECONDS = int(os.getenv('MOREAPP_AUTO_SYNC_INTERVAL_SECONDS', '300'))
MOREAPP_AUTO_REFRESH_SECONDS = int(os.getenv('MOREAPP_AUTO_REFRESH_SECONDS', '300'))
ORDENES_TRABAJO_HABILITADAS = os.getenv('ORDENES_TRABAJO_HABILITADAS', 'true').strip().lower() == 'true'
MOREAPP_INCREMENTAL_SCAN_ENABLED = os.getenv('MOREAPP_INCREMENTAL_SCAN_ENABLED', 'true').strip().lower() == 'true'
MOREAPP_INCREMENTAL_LOOKBACK = int(os.getenv('MOREAPP_INCREMENTAL_LOOKBACK', '2'))
# Límites para sync por HTTP (evitar Request Timeout del hosting)
MOREAPP_WEB_SYNC_MAX_SEGUNDOS = int(os.getenv('MOREAPP_WEB_SYNC_MAX_SEGUNDOS', '35'))
MOREAPP_WEB_SYNC_MAX_ARCHIVOS = int(os.getenv('MOREAPP_WEB_SYNC_MAX_ARCHIVOS', '60'))
MOREAPP_WEB_SKIP_DUPLICATE_REPROCESS = os.getenv('MOREAPP_WEB_SKIP_DUPLICATE_REPROCESS', 'true').strip().lower() == 'true'
# Si no hay estado incremental: solo los últimos N correlativos por formulario
MOREAPP_FIRST_SCAN_TAIL = int(os.getenv('MOREAPP_FIRST_SCAN_TAIL', '40'))


# Modulo de ordenes de trabajo (fase de desactivacion segura)
ORDENES_TRABAJO_ENABLED = os.getenv('ORDENES_TRABAJO_ENABLED', 'false').strip().lower() == 'true'

# Configuracion API para integracion con MoreApp (Webhooks)
# Token de seguridad para validar solicitudes de MoreApp
MOREAPP_WEBHOOK_SECRET = os.getenv('MOREAPP_WEBHOOK_SECRET', 'nC1IeThyHxR1h_DoZ2f8-KG9kGB3Ca98wZPkTiilQA4=')

# Directorio raíz donde MoreApp deposita los registros (vía FTPS)
# Estructura: {MOREAPP_REGISTROS_DIR}/{customerId}/{formName}/{correlativo}/registration.json
MOREAPP_REGISTROS_DIR = os.getenv('MOREAPP_REGISTROS_DIR', str(BASE_DIR / 'Registros'))

# Ejemplo (usa TUS datos reales):
# FTPS_HOST=ftp.tuservidor.com
# FTPS_PORT=21
# FTPS_USERNAME=tu_usuario
# FTPS_PASSWORD=tu_contrasena
# FTPS_BASE_PATH=/
# FTPS_PASSIVE_MODE=True
