# Generated by Django 6.0 on 2025-12-18 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('REASIGNADA', 'Reasignada'), ('MANTENIMIENTO', 'Mantenimiento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tecnico_solicito_reasignacion', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsable', models.ForeignKey(limit_choices_to={'rol': 'TECNICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_responsable', to=settings.AUTH_USER_MODEL)),
                ('tecnicos_equipo', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'TECNICO'}, related_name='ordenes_equipo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
