# Generated by Django 5.2.7 on 2026-01-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ordenes_trabajo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
            },
        ),
        migrations.CreateModel(
            name='OrdenHerramientaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('obligatoria', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Herramientas Requeridas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('BAJA', 'Baja')], default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='observacion_validacion',
            field=models.TextField(blank=True, help_text='Observaciones si la validación rechaza la OT'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='validada_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA', 'Asignada'), ('EN_EJECUCION', 'En ejecución'), ('REASIGNADA', 'Reasignada'), ('MANTENIMIENTO', 'Mantenimiento'), ('PENDIENTE_VALIDACION', 'Pendiente validación'), ('VALIDADA', 'Validada'), ('OBSERVADA', 'Observada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnicos_equipo',
            field=models.ManyToManyField(blank=True, help_text='Otros técnicos que participan (además del responsable)', limit_choices_to={'rol': 'TECNICO'}, related_name='ordenes_equipo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdjuntoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografía'), ('FPT', 'FPT (MoreApp)'), ('PDF', 'PDF'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(help_text='Archivo subido', upload_to='ordenes_adjuntos/%Y/%m/%d/')),
                ('url_externa', models.URLField(blank=True, help_text='URL remota si viene de MoreApp u otro servicio')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('hash_archivo', models.CharField(blank=True, help_text='Hash SHA256 para evitar duplicados', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional (de MoreApp u otra integración)')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='ordenes_trabajo.ordentrabajo')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adjuntos de Órdenes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('miembros', models.ManyToManyField(help_text='Técnicos que forman parte del equipo (2 a 4 recomendado)', limit_choices_to={'rol': 'TECNICO'}, related_name='equipos_miembro', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(limit_choices_to={'rol': 'TECNICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Equipos de Trabajo',
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='equipo_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='ordenes_trabajo.equipotrabajo'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='ordenes_tra_estado_a5ff74_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['tecnico_responsable'], name='ordenes_tra_tecnico_ae1204_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['cliente'], name='ordenes_tra_cliente_adc94a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['-fecha_creacion'], name='ordenes_tra_fecha_c_dff61f_idx'),
        ),
        migrations.AddField(
            model_name='ordenherramientarequerida',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_uso', to='ordenes_trabajo.herramienta'),
        ),
        migrations.AddField(
            model_name='ordenherramientarequerida',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_requeridas', to='ordenes_trabajo.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='equipotrabajo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='ordenes_trabajo.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='adjuntoorden',
            index=models.Index(fields=['orden'], name='ordenes_tra_orden_i_a79df8_idx'),
        ),
        migrations.AddIndex(
            model_name='adjuntoorden',
            index=models.Index(fields=['tipo'], name='ordenes_tra_tipo_686830_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenherramientarequerida',
            unique_together={('orden', 'herramienta')},
        ),
    ]
