# Generated by Django 5.2.7 on 2026-01-27 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_modem_imei_modem_ip_modem_irregularidad_and_more'),
        ('ordenes_trabajo', '0002_herramienta_ordenherramientarequerida_vehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_fin_ejecucion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el técnico finalizó el trabajo', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_inicio_ejecucion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el técnico inició el trabajo', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='medidor',
            field=models.ForeignKey(blank=True, help_text='Medidor instalado/cambiado/retirado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='inventario.medidor'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='modem',
            field=models.ForeignKey(blank=True, help_text='Módem instalado/cambiado/retirado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='inventario.modem'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='observaciones_tecnicas',
            field=models.TextField(blank=True, help_text='Observaciones del técnico durante la ejecución'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='simcard',
            field=models.ForeignKey(blank=True, help_text='SIM Card utilizada en el trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='inventario.simcard'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_trabajo',
            field=models.CharField(choices=[('INSTALACION', 'Instalación'), ('CAMBIO', 'Cambio de equipo'), ('RETIRO', 'Retiro'), ('MANTENCION', 'Mantención'), ('REPARACION', 'Reparación'), ('INSPECCION', 'Inspección'), ('CONFIGURACION', 'Configuración'), ('OTRO', 'Otro')], default='INSTALACION', help_text='Tipo de trabajo a realizar', max_length=30),
        ),
        migrations.CreateModel(
            name='IntegracionMoreApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreapp_submission_id', models.CharField(help_text='ID único del submission de MoreApp', max_length=255, unique=True)),
                ('estado_sincronizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('DUPLICADO', 'Duplicado')], default='PENDIENTE', max_length=20)),
                ('datos_recibidos', models.JSONField(default=dict, help_text='Payload completo recibido desde MoreApp')),
                ('datos_procesados', models.JSONField(blank=True, default=dict, help_text='Datos extraídos y procesados')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la sincronización falló')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('actualizo_cliente', models.BooleanField(default=False)),
                ('actualizo_equipos', models.BooleanField(default=False)),
                ('creo_adjuntos', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_moreapp', to='ordenes_trabajo.ordentrabajo')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_procesadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integración MoreApp',
                'verbose_name_plural': 'Integraciones MoreApp',
                'ordering': ['-fecha_recepcion'],
                'indexes': [models.Index(fields=['moreapp_submission_id'], name='ordenes_tra_moreapp_a30e4f_idx'), models.Index(fields=['estado_sincronizacion'], name='ordenes_tra_estado__27f6af_idx'), models.Index(fields=['-fecha_recepcion'], name='ordenes_tra_fecha_r_433496_idx')],
            },
        ),
    ]
