# Generated by Django 5.2.7 on 2026-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0003_ordentrabajo_fecha_fin_ejecucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='ediciones_tecnico',
            field=models.IntegerField(default=0, help_text='Número de veces que el técnico ha editado la orden (máximo 2)'),
        ),
    ]
