# Generated by Django 4.2.29 on 2026-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0004_ordentrabajo_ediciones_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionmoreapp',
            name='alerta_doble_trabajo',
            field=models.BooleanField(default=False, help_text='True si se detectó posible trabajo duplicado al mismo cliente'),
        ),
        migrations.AddField(
            model_name='integracionmoreapp',
            name='descripcion_alerta',
            field=models.TextField(blank=True, help_text='Descripción del motivo de la alerta de doble trabajo'),
        ),
        migrations.AddField(
            model_name='integracionmoreapp',
            name='nombre_formulario',
            field=models.CharField(blank=True, help_text='Nombre del formulario (info.formName del JSON)', max_length=255),
        ),
        migrations.AddField(
            model_name='integracionmoreapp',
            name='numero_correlativo',
            field=models.IntegerField(blank=True, help_text='Número de carpeta correlativa MoreApp (1, 2, 3, ...)', null=True),
        ),
        migrations.AddField(
            model_name='integracionmoreapp',
            name='ruta_carpeta',
            field=models.CharField(blank=True, help_text='Ruta local de la carpeta correlativa del registro', max_length=500),
        ),
        migrations.AlterField(
            model_name='integracionmoreapp',
            name='estado_sincronizacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PROCESADO', 'Procesado'), ('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('ERROR_JSON', 'Error - JSON inválido'), ('ERROR_LECTURA', 'Error - Lectura'), ('DUPLICADO', 'Duplicado'), ('ALERTA_REVISION', 'Alerta - Revisión requerida')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='integracionmoreapp',
            index=models.Index(fields=['alerta_doble_trabajo'], name='ordenes_tra_alerta__dd93bc_idx'),
        ),
    ]
