# Generated by Django 4.2.29 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0005_integracionmoreapp_alerta_doble_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionmoreapp',
            name='estado_revision',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('CON_ADVERTENCIA', 'Con advertencia'), ('REVISADO', 'Revisado OK'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE', help_text='Estado de revisión operativa del registro', max_length=20),
        ),
        migrations.AddIndex(
            model_name='integracionmoreapp',
            index=models.Index(fields=['estado_revision'], name='ordenes_tra_estado__7a6e96_idx'),
        ),
    ]
