# Generated by Django 4.2.29 on 2026-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0006_integracionmoreapp_estado_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADO', 'Realizado'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=30),
        ),
    ]
