# Generated by Django 4.2.30 on 2026-07-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0008_evidencias_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='validada_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'AUDITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_validadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
