# Generated by Django 4.2.30 on 2026-07-10 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0009_alter_ordentrabajo_validada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='orden_origen',
            field=models.ForeignKey(blank=True, help_text='OT anterior cuando esta orden se creó por observación en validación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_derivadas', to='ordenes_trabajo.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='validada_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ADMINISTRATIVO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_validadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
