# Generated by Django 4.2.30 on 2026-07-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0010_orden_origen_y_validacion_administrativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['id'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
    ]
