# Generated by Django 4.2.30 on 2026-07-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0011_alter_ordentrabajo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionmoreapp',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: oculto en reportes; sync no lo reprocesa ni recrea'),
        ),
        migrations.AddField(
            model_name='integracionmoreapp',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moreapp_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracionmoreapp',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: oculta en listados, histórico en movimientos'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='integracionmoreapp',
            index=models.Index(fields=['eliminado'], name='ordenes_tra_elimina_963e05_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['eliminado'], name='ordenes_tra_elimina_48615b_idx'),
        ),
    ]
