# Generated by Django 4.2.30 on 2026-07-17 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0012_soft_delete_y_snapshot_eliminaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_reasignacion',
            field=models.TextField(blank=True, help_text='Comentario obligatorio al reasignar el técnico responsable'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='validada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario (admin/administrativo) que registró la validación con su propia cuenta', limit_choices_to={'rol__in': ['ADMIN', 'ADMINISTRATIVO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_validadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
