# Generated by Django 4.2.30 on 2026-07-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0013_validacion_reasignacion_y_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroValidacionOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VALIDADA', 'Validada (aprobada)'), ('OBSERVADA', 'Observada (rechazada)'), ('REASIGNADA', 'Reasignación de técnico')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=40)),
                ('estado_nuevo', models.CharField(blank=True, max_length=40)),
                ('detalle_extra', models.CharField(blank=True, help_text='Ej. técnico anterior → nuevo técnico', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_validacion', to='ordenes_trabajo.ordentrabajo')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_validacion_ot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de validación OT',
                'verbose_name_plural': 'Registros de validación OT',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['orden', '-fecha'], name='ordenes_tra_orden_i_4fc152_idx'), models.Index(fields=['accion', '-fecha'], name='ordenes_tra_accion_6f3c67_idx')],
            },
        ),
    ]
