# Generated by Django 4.2.30 on 2026-07-22 15:41

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0014_registro_validacion_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntoorden',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo subido en Registros/Evidencias (opcional si hay URL externa)', null=True, storage=config.storage.EvidenciasStorage(), upload_to=config.storage.evidencia_upload_to),
        ),
    ]
