# Generated by Django 4.2.30 on 2026-07-30 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0016_informecliente_origen_respaldo_moreapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionComunicacionOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida')], db_index=True, default='SOLICITADA', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones_solicitud', models.TextField(blank=True, help_text='Nota del técnico al solicitar la validación')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del administrativo sobre el resultado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_comunicacion', to='ordenes_trabajo.ordentrabajo')),
                ('solicitado_por', models.ForeignKey(blank=True, help_text='Técnico (u oficina) que pidió la prueba', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_comunicacion_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, help_text='Administrativo que registró el resultado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_comunicacion_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación de comunicación OT',
                'verbose_name_plural': 'Validaciones de comunicación OT',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['orden', '-fecha_solicitud'], name='ordenes_tra_orden_i_e60225_idx'), models.Index(fields=['estado', '-fecha_solicitud'], name='ordenes_tra_estado_9f8542_idx')],
            },
        ),
    ]
