# Generated by Django 4.2.30 on 2026-07-31 14:39

import config.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0011_carga_administrativa'),
        ('ordenes_trabajo', '0017_validacion_comunicacion_ot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCambioMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor_retirado_serie', models.CharField(blank=True, max_length=100)),
                ('medidor_retirado_marca', models.CharField(blank=True, max_length=100)),
                ('medidor_instalado_serie', models.CharField(max_length=100)),
                ('medidor_instalado_marca', models.CharField(blank=True, max_length=100)),
                ('fecha_cambio', models.DateTimeField(help_text='Fecha y hora del cambio de medidor')),
                ('nombre_firmante_cliente', models.CharField(blank=True, help_text='Nombre de quien firma por el cliente', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('firma_cliente', models.FileField(blank=True, help_text='Imagen PNG de la firma del cliente', null=True, storage=config.storage.EvidenciasStorage(), upload_to=config.storage.evidencia_upload_to)),
                ('firma_tecnico', models.FileField(blank=True, help_text='Imagen PNG de la firma del técnico (opcional)', null=True, storage=config.storage.EvidenciasStorage(), upload_to=config.storage.evidencia_upload_to)),
                ('pdf', models.FileField(blank=True, help_text='PDF del comprobante generado o subido', null=True, storage=config.storage.EvidenciasStorage(), upload_to=config.storage.evidencia_upload_to)),
                ('pdf_subido', models.BooleanField(default=False, help_text='True si el PDF se subió firmado externamente en lugar de generarse')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_cambio_medidor', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_cambio_creados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_cambio_medidor', to='ordenes_trabajo.ordentrabajo')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_cambio_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante de cambio de medidor',
                'verbose_name_plural': 'Comprobantes de cambio de medidor',
                'ordering': ['-fecha_cambio', '-fecha_creacion'],
                'indexes': [models.Index(fields=['orden', '-fecha_cambio'], name='ordenes_tra_orden_i_a8a521_idx'), models.Index(fields=['cliente', '-fecha_cambio'], name='ordenes_tra_cliente_b0d7fc_idx')],
            },
        ),
    ]
