# Generated by Django 4.2.30 on 2026-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0018_comprobante_cambio_medidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecambiomedidor',
            name='medidor_instalado_serie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
