# Generated by Django 4.2.30 on 2026-08-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0019_comprobante_serie_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipotrabajo',
            name='miembros',
        ),
        migrations.RemoveField(
            model_name='equipotrabajo',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='equipotrabajo',
            name='vehiculo',
        ),
        migrations.AlterUniqueTogether(
            name='ordenherramientarequerida',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ordenherramientarequerida',
            name='herramienta',
        ),
        migrations.RemoveField(
            model_name='ordenherramientarequerida',
            name='orden',
        ),
        migrations.RemoveIndex(
            model_name='integracionmoreapp',
            name='ordenes_tra_moreapp_a30e4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='integracionmoreapp',
            name='ordenes_tra_estado__7a6e96_idx',
        ),
        migrations.RemoveIndex(
            model_name='integracionmoreapp',
            name='ordenes_tra_elimina_963e05_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='ordenes_tra_elimina_48615b_idx',
        ),
        migrations.RemoveField(
            model_name='adjuntoorden',
            name='hash_archivo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='equipo_trabajo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tecnicos_equipo',
        ),
        migrations.DeleteModel(
            name='EquipoTrabajo',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
        migrations.DeleteModel(
            name='OrdenHerramientaRequerida',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
