# Generated by Django 4.2.30 on 2026-08-24 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes_trabajo', '0021_ordentrabajo_proyecto_carga_administrativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['TECNICO', 'ADMINISTRATIVO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
