# Generated by Django 5.2.7 on 2026-01-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='medidor_actual',
            field=models.OneToOneField(blank=True, help_text='Medidor instalado actualmente en este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_actual', to='inventario.medidor'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_cliente'], name='clientes_cl_numero__69cca7_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx'),
        ),
    ]
