# Generated by Django 4.2.29 on 2026-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(blank=True, help_text='Fecha de registro o instalación del cliente', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ip',
            field=models.CharField(blank=True, help_text='Dirección IP asignada al cliente/modem', max_length=45),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modem',
            field=models.CharField(blank=True, help_text='Modelo o información del módem instalado', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puerto',
            field=models.CharField(blank=True, help_text='Puerto o número de puerto de la conexión', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='trabajo',
            field=models.CharField(blank=True, help_text='Descripción del trabajo realizado o a realizar', max_length=255),
        ),
    ]
