# Generated by Django 4.2.30 on 2026-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_fecha_registro_cliente_ip_cliente_modem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad del cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='client_type',
            field=models.CharField(blank=True, help_text='Tipo de cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Nombre del cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='installation_address',
            field=models.CharField(blank=True, help_text='Dirección de instalación del cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='meter_manufacturer_id',
            field=models.CharField(blank=True, help_text='Fabricante o identificador del medidor', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='meter_serial_n_1',
            field=models.CharField(blank=True, help_text='Número de serie del medidor', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='note',
            field=models.TextField(blank=True, help_text='Nota adicional para el cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pod',
            field=models.CharField(blank=True, help_text='Punto de entrega (POD) del cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, help_text='Sector o área geográfica del cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_suministro',
            field=models.CharField(blank=True, help_text='Tipo de suministro asociado al cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_acceso',
            field=models.CharField(blank=True, help_text='Último acceso registrado', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_perfil_carga',
            field=models.CharField(blank=True, help_text='Último perfil de carga', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_perfil_instrumentacion',
            field=models.CharField(blank=True, help_text='Último perfil de instrumentación', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_registro_facturacion',
            field=models.CharField(blank=True, help_text='Último registro de facturación', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_reset',
            field=models.CharField(blank=True, help_text='Último reset registrado', max_length=100),
        ),
    ]
