# Generated by Django 4.2.30 on 2026-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_city_cliente_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='proyecto',
            field=models.CharField(blank=True, help_text='Proyecto asociado al cliente', max_length=255),
        ),
    ]
