# Generated by Django 4.2.30 on 2026-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad del cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='client_type',
            field=models.CharField(blank=True, help_text='Tipo de cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Nombre del cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='installation_address',
            field=models.CharField(blank=True, help_text='Dirección de instalación del cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ip',
            field=models.CharField(blank=True, help_text='Dirección IP asignada al cliente/modem', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meter_manufacturer_id',
            field=models.CharField(blank=True, help_text='Fabricante o identificador del medidor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meter_serial_n_1',
            field=models.CharField(blank=True, help_text='Número de serie del medidor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modem',
            field=models.CharField(blank=True, help_text='Modelo o información del módem instalado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='note',
            field=models.TextField(blank=True, help_text='Nota adicional para el cliente', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pod',
            field=models.CharField(blank=True, help_text='Punto de entrega (POD) del cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proyecto',
            field=models.CharField(blank=True, help_text='Proyecto asociado al cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='puerto',
            field=models.CharField(blank=True, help_text='Puerto o número de puerto de la conexión', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='referencia',
            field=models.TextField(blank=True, help_text='Notas adicionales para ubicación (ej: "Puerta roja, cerca del almacén")', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, help_text='Sector o área geográfica del cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_suministro',
            field=models.CharField(blank=True, help_text='Tipo de suministro asociado al cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='trabajo',
            field=models.CharField(blank=True, help_text='Descripción del trabajo realizado o a realizar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_acceso',
            field=models.CharField(blank=True, help_text='Último acceso registrado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_perfil_carga',
            field=models.CharField(blank=True, help_text='Último perfil de carga', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_perfil_instrumentacion',
            field=models.CharField(blank=True, help_text='Último perfil de instrumentación', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_registro_facturacion',
            field=models.CharField(blank=True, help_text='Último registro de facturación', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_reset',
            field=models.CharField(blank=True, help_text='Último reset registrado', max_length=100, null=True),
        ),
    ]
