# Generated by Django 4.2.30 on 2026-07-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0007_cliente_campos_pdf_punto_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de soft-delete (activo=False)', null=True),
        ),
    ]
