# Generated by Django 4.2.30 on 2026-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_proyecto_historial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clienteproyectohistorial',
            new_name='clientes_cl_cliente_362486_idx',
            old_name='clientes_cl_cliente_6a0f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='clienteproyectohistorial',
            new_name='clientes_cl_proyect_f9ede8_idx',
            old_name='clientes_cl_proyect_7b1c2d_idx',
        ),
        migrations.AlterField(
            model_name='clienteproyectohistorial',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Cuándo dejó de ser el proyecto actual (cambio a otro / cierre). Vacío = aún vigente o sin cierre registrado', null=True),
        ),
    ]
