# Generated by Django 4.2.30 on 2026-07-30 20:18
#
# Nota operativa (hosting):
# Los RenameIndex auto-generados fallaban con:
#   ValueError: No index named clientes_cl_cliente_6a0f0f_idx on model ClienteProyectoHistorial
# porque en algunos entornos el estado/BD no coincide con esos nombres.
# Los índices ya existen desde 0010; solo se actualiza el help_text de fecha_fin.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_proyecto_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteproyectohistorial',
            name='fecha_fin',
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    'Cuándo dejó de ser el proyecto actual (cambio a otro / cierre). '
                    'Vacío = aún vigente o sin cierre registrado'
                ),
                null=True,
            ),
        ),
    ]
