# Generated by Django 4.2.30 on 2026-08-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_carga_administrativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pod',
        ),
    ]
