# Generated by Django 4.2.30 on 2026-08-21 17:16

import config.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0013_cliente_proyecto_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografía / captura de pantalla'), ('PDF', 'PDF'), ('OTRO', 'Otro')], default='FOTO', max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(help_text='Archivo en Registros/Evidencias/adjuntos_clientes', storage=config.storage.EvidenciasStorage(), upload_to=config.storage.evidencia_upload_to)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('hash_archivo', models.CharField(blank=True, max_length=64)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='clientes.cliente')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_cliente_eliminados', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_cliente_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de cliente',
                'verbose_name_plural': 'Adjuntos de clientes',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['cliente'], name='clientes_cl_cliente_86942f_idx'), models.Index(fields=['tipo'], name='clientes_cl_tipo_6e6259_idx'), models.Index(fields=['cliente', 'eliminado'], name='clientes_cl_cliente_ab8bac_idx')],
            },
        ),
    ]
